# USER ENDPOINTS

### GET user
GET http://localhost:3001/user/get?id=67471858cf965e445addf6b8

### DELETE user
DELETE http://localhost:3001/user/delete?id=67449d84006e58b6c1b07cec

### UPDATE user
PUT http://localhost:3001/user/update?id=6747100ec1c469d6fea8b9f4
Content-Type: application/json

{
	"name": "New name",
	"surname": "New awakedavakevra",
	"photo": "New photo"
}

### LIST user
GET http://localhost:3001/user/list

### CREATE user
POST http://localhost:3001/user/create
Content-Type: application/json

{
	"name": "Kladestyn",
	"surname": "Awakedavra",
	"photo": "photo"
}

### LOGIN user
POST http://localhost:3001/user/login
Content-Type: application/json

{
	"name": "romulus",
	"surname": "augustus",
	"photo": "photo1"
}

#===================================================================================================#

# EVENT ENDPOINTS
### Define the bearer token and access token
@accessToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicm9tdWx1cyIsInN1cm5hbWUiOiJhdWd1c3R1cyIsInBob3RvIjoicGhvdG8xIiwiaWF0IjoxNzM0MTc1MDQ5LCJleHAiOjE3MzQxNzU5NDl9.HBhlw8yRswW0adR3vC7aQnJUe4fkmrr-6HHM4y1EnuQ

### GET event
GET http://localhost:3001/event/get?id=67471858cf965e445addf6b8
Authorization: {{accessToken}}

### DELETE event
DELETE http://localhost:3001/event/delete?id=67483a4850dba461d19f33af
Authorization: {{accessToken}}

### UPDATE event
PUT http://localhost:3001/event/update?id=6748594909d8d5183f95aae4
Authorization: {{accessToken}}
Content-Type: application/json

  {
    "name": "Non-Pregnants",
    "members": [
      "674450c8e2f3f5cbcf033fff",
      "674450c8e2f3f5cbcf033ccc"
    ],
    "items": [
      {
        "name": "toys",
        "state": "done"
      },
      {
        "name": "milk",
        "state": "pending"
      }
    ],
    "owner": "674450c8e2f3f5cbcf033aaa",
    "archived": false,
    "icon": "x"
  }

### LIST event
GET http://localhost:3001/event/list
Authorization: {{accessToken}}

### CREATE event
POST http://localhost:3001/event/create
Authorization: {{accessToken}}
Content-Type: application/json

{
	"name": "Pregnants",
	"members": [
		"674450c8e2f3f5cbcf033fff",
		"674450c8e2f3f5cbcf033ccc"
	],
	"items": [
		{
			"name": "bread",
			"state": "pending"
		},
		{
			"name": "milk",
			"state": "done"
		}
	],
	"owner": "674450c8e2f3f5cbcf033aaa",
	"archived": false,
	"icon": "a"
}
